version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql

# docker exec -it redis-lock redis-cli 접속 후 ping 으로 확인
  redis:
    image: redis:7
    container_name: redis-lock
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge