erDiagram
    Queue ||--o{ Reservation : makes
    Queue ||--o{ Payment : has

    Queue {
        int id PK
        int userId FK
        string token
        datetime expiredAt
        enum type "ACTIVE | WAITING"
        datetime createdAt
    }

    Concert ||--o{ Schedule : has
    Concert {
        int id PK
        string name
        string description
    }

    Schedule ||--o{ Seat : contains
    Schedule {
        int id PK
        int concertId FK
        date scheduleDate
        time startTime
    }

    Seat ||--o{ Reservation : has
    Seat {
        int id PK
        int scheduleId FK
        string seatNumber
        float price
        enum status "AVAILABLE | RESERVED"
    }

    Reservation ||--|| Payment : has_payment
    Reservation {
        int id PK
        int userId FK
        int seatId FK
        int transactionId FK
        enum status "SUCCESS | FAILED"
        datetime reservedAt
        datetime expiredAt
    }

    Payment {
        int id PK
        int userId FK
        enum type "PAYMENT | CHARGE"
        float amount
        float balance
        enum status "SUCCESS | FAILED | PENDING"
        datetime processedAt
    }
