sequenceDiagram
    participant Facade as PaymentFacade
    participant BalanceService as BalanceService
    participant ChargeService as ChargeService
    participant PaymentService as PaymentService

    Facade->>+BalanceService: checkBalance()
    alt balance sufficient
        Facade->>+PaymentService: makePayment()
    else
        Facade->>+ChargeService: chargeBalance()
        alt charge succeed
            Facade->>+PaymentService: makePayment()
        end
    end
    PaymentService-->>-Facade: return true
