sequenceDiagram
    participant Controller as SeatController
    participant Service as SeatService
    participant concertScheduleRepository as concertScheduleRepository
    participant SeatRepository as SeatRepository

    Controller->>+Service: validateToken()
    alt findToken() !== true
        Service->>+concertScheduleRepository: findDate()
        alt findDate() !== true
            Service->>+SeatRepository: findSeat()
        end
    end
    SeatRepository-->>-Service: return seat, date
    Service-->>-Controller: return seat, date
